config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :task_types do
        collection do
        #get 'task_types/search', to: 'task_types#search'
        get 'search' #, to: 'task_types#search'
      end
    end
    
    #get 'task_types/search', to: 'task_types#search'
    #get 'clm_work_items/search', to: 'clm_work_items#search'
    
    resources :clm_work_items do
        collection do
            get 'search'
        end
    end
    #resources :cards
    resources :emps
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    root "welcome#index"
    
    resources :emps do
        resources :cards
    end
  
  
    get 'sign_up', to: 'emps#new'
    post 'sign_up', to: 'emps#create'
    
    get 'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create', as: 'log_in'
    delete 'logout', to: 'sessions#destroy'
    
    get 'password', to: 'passwords#edit', as: 'edit_password'
    patch 'password', to: 'passwords#update'
    get 'password/reset', to: 'password_resets#new'
    post 'password/reset', to: 'password_resets#create'
    get 'password/reset/edit', to: 'password_resets#edit'
    patch 'password/reset/edit', to: 'password_resets#update'

end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_action :set_task_type, only: %i[ show edit update destroy ]
  before_action :force_json, only: :search

  # GET /task_types or /task_types.json
  def index
    @task_types = TaskType.all
  end

  # GET /task_types/1 or /task_types/1.json
  def show
  end

  # GET /task_types/new
  def new
    @task_type = TaskType.new
  end

  # GET /task_types/1/edit
  def edit
  end

  # POST /task_types or /task_types.json
  def create
    @task_type = TaskType.new(task_type_params)

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: "Task type was successfully created." }
        format.json { render :show, status: :created, location: @task_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_types/1 or /task_types/1.json
  def update
    respond_to do |format|
      if @task_type.update(task_type_params)
        format.html { redirect_to @task_type, notice: "Task type was successfully updated." }
        format.json { render :show, status: :ok, location: @task_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1 or /task_types/1.json
  def destroy
    @task_type.destroy
    respond_to do |format|
      format.html { redirect_to task_types_url, notice: "Task type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    q = params[:q].downcase
    @tasktypes = TaskType.where("name ILIKE ? ", "%#{q}%").limit(5)
    puts 'Ez search'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_type
      @task_type = TaskType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_type_params
      params.require(:task_type).permit(:id, :name)
      #params.fetch(:task_type, {})
    end
    
    def force_json
      request.format = :json
    end
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/views/task_types/_form.html.erb
<%= form_with(model: task_type) do |form| %>
  <% if task_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_type.errors.count, "error") %> prohibited this task_type from being saved:</h2>

      <ul>
        <% task_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>  
  
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_types/edit.html.erb
<h1>Editing Task Type</h1>

<%= render 'form', task_type: @task_type %>

<%= link_to 'Show', @task_type %> |
<%= link_to 'Back', task_types_path %>

app/views/task_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="2"></th>
      <th>Id</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @task_types.each do |task_type| %>
      <tr>
        <td><%= task_type.id %></td>
        <td><%= task_type.name %></td>
        
        <td><%= link_to 'Show', task_type %></td>
        <td><%= link_to 'Edit', edit_task_type_path(task_type) %></td>
        <td><%= link_to 'Destroy', task_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Type', new_task_type_path %>

app/views/task_types/new.html.erb
<h1>New Task Type</h1>

<%= render 'form', task_type: @task_type %>

<%= link_to 'Back', task_types_path %>

app/views/task_types/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>ID:</strong>
  <%= @task_type.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task_type.name %>
</p>

<%= link_to 'Edit', edit_task_type_path(@task_type) %> |
<%= link_to 'Back', task_types_path %>