config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :task_types do
        collection do
        #get 'task_types/search', to: 'task_types#search'
        get 'search' #, to: 'task_types#search'
      end
    end
    
    #get 'task_types/search', to: 'task_types#search'
    #get 'clm_work_items/search', to: 'clm_work_items#search'
    
    resources :clm_work_items do
        collection do
            get 'search'
        end
    end
    #resources :cards
    resources :emps
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    root "welcome#index"
    
    resources :emps do
        resources :cards
    end
  
  
    get 'sign_up', to: 'emps#new'
    post 'sign_up', to: 'emps#create'
    
    get 'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create', as: 'log_in'
    delete 'logout', to: 'sessions#destroy'
    
    get 'password', to: 'passwords#edit', as: 'edit_password'
    patch 'password', to: 'passwords#update'
    get 'password/reset', to: 'password_resets#new'
    post 'password/reset', to: 'password_resets#create'
    get 'password/reset/edit', to: 'password_resets#edit'
    patch 'password/reset/edit', to: 'password_resets#update'

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :emp
  
  has_many :entries, :dependent => :destroy
  accepts_nested_attributes_for :entries, :reject_if => lambda { |a| a[:duration].blank? }, :allow_destroy => true

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :get_emp
  before_action :set_card, only: [:show, :edit, :update, :destroy]

   
    def index
        #@emp = Emp.find(params[:emp_id])
        @cards = @emp.cards
    end 
    
    def new 
       @card = @emp.cards.build
       
       default_start = Date.today.beginning_of_week(start_day = :sunday)
       default_end = Date.today.beginning_of_week(start_day = :sunday)
       
       default_start = Time.zone.at(default_start.to_time).to_datetime
       default_end = Time.zone.at(default_end.to_time).to_datetime

       default_start = default_start.change(hour: 8)
       default_end = default_end.change(hour: 16)
       
       @card.start_time = default_start
        5.times do
          entry = @card.entries.build
          entry.start_time = default_start
          entry.end_time = default_end
          
          
          
          diff = ((default_end- default_start) * 24 ).round 
          entry.duration = '0d '+ diff.to_s + 'h 0m'
          #byebug
          

          #puts default_end.to_s() + ' ' + default_start.to_s() 
          
          default_start = default_start + 1
          default_end = default_end + 1
          #4.times { question.answers.build }
        end
  
    end 
    
    def create
      #@emp = Emp.find(params[:emp_id])
      #byebug
      #@card = @emp.cards.create(card_params)
      #@card =
      #puts @emp.id
      #@emp.cards.create!(card_params)
      #redirect_to emp_path(@emp)
     
      #@card = @emp.cards.build(card_params)
      @card = Card.new(card_params)
      respond_to do |format|
        if @card.save
          format.html { redirect_to emp_path(@emp), notice: 'Card was successfully created.' }
          format.json { render :show, status: :created, location: @card }
        else
          format.html { render :new }
          format.json { render json: @card.errors, status: :unprocessable_entity }
        end
      end
    end
    
    # PATCH/PUT /card/1
  # PATCH/PUT /card/1.json
    def update
      respond_to do |format|
        if @card.update(card_params)
          format.html { redirect_to emp_path(@emp), notice: 'Card was successfully updated.' }
          format.json { render :show, status: :ok, location: @card }
        else
          format.html { render :edit }
          format.json { render json: @card.errors, status: :unprocessable_entity }
        end
      end
    end
    
      # DELETE /cards/1 or /cards/1.json
    def destroy
        #@card = Card.find(params[:id])
        @card.destroy
        respond_to do |format|
          format.html { redirect_to emp_path(@emp), notice: "card was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    private
    
    def card_params

      params.require(:card).permit(:emp_id, :clm_work_item_id, :task_type_id, :start_time, :end_time, :duration, :comment , 
      { entries_attributes: [ :_destroy, :card_id, :clm_work_item_id, :task_type_id, :start_time, :start_time_t , :end_time, :end_time_t, :duration, :comment]} )
    end
    
    def get_emp
        @emp = Emp.find(params[:emp_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = @emp.cards.find(params[:id])
    end
    
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/cards/_card.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Employee</th>
      <th>CLM Work Item</th>
      <th>Task Type</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Duration</th>
      <th>Comment</th>
      <th>Actions</th>
      <th colspan="9"></th>
    </tr>
  </thead>
  <tbody>
  
<!--% if !@emp.cards.blank? %-->
      <!--% @emp.cards.each do |c| %-->
          <!--% for c in @emp.cards % -->
          <!--% puts @emp.cards.size %-->
          <tr>
            <td><%= c.id %></td>
            <td><%= c.emp_id %></td>
            <td><%= c.clm_work_item_id %></td>
            <td><%= c.task_type_id %></td>
            <td><%= c.start_time %></td>
            <td><%= c.end_time %></td>
            <td><%= c.duration %></td>
            <td><%= c.comment %></td>
            <td><%= link_to 'Edit ', edit_emp_card_path(@emp, c) %></td>
            <td><%= link_to 'Destroy ', [@emp, c], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <!-- % end % -->
<!--% else %-->
<!--% end %-->
  </tbody>
</table>

<h2>Entries</h2>
<!--%= render @emp.cards %-->
<%= render partial: "/cards/entry", collection: c.entries , as: :e || "There are no entries available."  %>

app/views/cards/_entry.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Card ID</th>
      <th>CLM Work Item</th>
      <th>Task Type</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Duration</th>
      <th>Comment</th>
      <th>Actions</th>
      <th colspan="9"></th>
    </tr>
  </thead>
  <tbody>
  
<!--% if !@emp.cards.blank? %-->
      <!--% @emp.cards.each do |c| %-->
          <!--% for c in @emp.cards % -->
          <!--% puts @emp.cards.size %-->
          <tr>
            <td><%= e.id %></td>
            <td><%= e.card_id %></td>
            <td><%= e.clm_work_item_id %></td>
            <td><%= e.task_type_id %></td>
            <td><%= e.start_time %></td>
            <td><%= e.end_time %></td>
            <td><%= e.duration %></td>
            <td><%= e.comment %></td>
            
            <td><!-- %= link_to 'Edit ', edit_emp_card_entry_path(@emp, c) % --></td>
            <td><!-- %= link_to 'Destroy ',  e, method: :delete, data: { confirm: 'Are you sure?' } %--></td>
          </tr>
      <!-- % end % -->
<!--% else %-->
<!--% end %-->
  </tbody>
</table>

app/views/cards/_entry_fields.erb
<!-- div class="fields"-->
<div class="nested-fields">

  
  <div class="field">
    <%= f.label :clm_work_item_id %>
    <%= f.text_field :clm_work_item_id , type: "search" , data: { behavior: "autocomplete-clm-work-items" } %>
    <%= f.hidden_field :clm_work_item_id %>
  </div>
  
  <div class="field">
    <%= f.label :task_type_id %>
    <%= f.text_field :task_type_id , type: "search" , data: { behavior: "autocomplete-clm-task-types" } %>
    <%= f.hidden_field :task_type_id %>
  </div>
  

    <div class="field">
      <%= f.label :start_time %>
      <%= f.text_field :start_time , class: 'flatpickr' %>
      <!--%= f.datetime_select :start_time , class: 'flatpickr' %-->
       
      <!--%= f.time_field  :start_time_t %-->
    </div>
    
    <div class="field">
      <%= f.label :end_time %>
      <%= f.text_field :end_time , class: 'flatpickr'%>
      <!--%= f.time_field  :end_time_t %-->
    </div>
    
    <div class="field">
      <%= f.label :duration %>
      <%= f.text_field :duration %>
    </div>
  
  
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>
  
  
  <%= f.label :task_type_id, "Remove Entry" %>
  <%= f.hidden_field :_destroy , class: "remove_fields" %>
  <!-- %= link_to_function "remove", "remove_fields(this)" %-->
  <%= link_to "remove" , {href: '#'}, class: "remove_fields" , id: :task_type_id %>



</div>

app/views/cards/_form.html.erb
<!-- %= form_with model: [ @emp, @emp.cards.build ] do |f| %-->

<%= form_with(model: [@emp, card], local: true) do |f| %>

<div id="card_form_fields">
<fieldset>

  
  <div class="field">
    <%= f.label :emp_id %>
    <%= f.text_field :emp_id %>
  </div>  
  
  <div class="field">
    <%= f.label :clm_work_item_id %>
    <%= f.text_field :clm_work_item_id %>
    <input id=<%= :clm_work_item_id %> type="search" placeholder="Enter name..." data-behavior="autocomplete">
  </div>
  
  <div class="field">
    <%= f.label :task_type_id %>
    <%= f.text_field :task_type_id %>
    <input id=<%= :task_type_id %> type="search" placeholder="Enter name..." data-behavior="autocomplete">
  </div>
  



  <div class="field">
    <%= f.label :start_time %>
    <%= f.text_field :start_time , class: 'flatpickr' %>
    <!--%= f.time_field  :start_time_t %-->
  </div>
  
  <div class="field">
    <%= f.label :end_time %>
    <%= f.text_field :end_time , class: 'flatpickr'%>
    <!--%= f.time_field  :end_time_t %-->
  </div>
  
  <div class="field">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>
  
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>
  
  <P>Entries</P>
  <%= f.fields_for :entries do |builder| %>
    <%= render "entry_fields", :f => builder %>
  <% end %>
  
  <p><%= link_to_add_fields "Add Entry", f, :entries %></p>

</fieldset>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end  %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card  %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', emp_cards_path(@emp) %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Employee ID</th>
      <th>CLM Work Item</th>
      <th>Task Type</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Duration</th>
      <th>Comment</th>
      <th colspan="12"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.id %></td>
        <td><%= card.emp_id %></td>
        <td><%= card.clm_work_item_id %></td>
        <td><%= card.task_type_id %></td>
        <td><%= card.start_time %></td>
        <td><%= card.end_time %></td>
        <td><%= card.duration %></td>
        <td><%= card.comment %></td>
        <td><%= link_to 'Show Card', [card.id] %></td>
        <td><!-- %= link_to 'Edit', edit_card_path(card) %--></td>
        <td><%= link_to 'Edit Card', edit_emp_card_path(@emp, card) %></td>
        <td><%= link_to 'Show Emp', [@emp] %> </td>

        <td><!--%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %--></td>
        <td><%= link_to 'Destroy Card', [@emp, card], method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_emp_card_path(@emp) %>

<!--%= link_to 'New Card', new_card_path %-->

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @card.id %>
</p>


<p>
  <strong>CLM Work Item :</strong>
  <%= @card.clm_work_item_id %>
</p>

<p>
  <strong>Task Type:</strong>
  <%= @card.task_type_id %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @card.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @card.end_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @card.duration %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @card.comment %>
</p>

<%= link_to 'Edit', edit_emp_card_path(@emp,@card) %> |
<%= link_to 'Back', emp_cards_path(@emp) %>