config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :task_types do
        collection do
        #get 'task_types/search', to: 'task_types#search'
        get 'search' #, to: 'task_types#search'
      end
    end
    
    #get 'task_types/search', to: 'task_types#search'
    #get 'clm_work_items/search', to: 'clm_work_items#search'
    
    resources :clm_work_items do
        collection do
            get 'search'
        end
    end
    #resources :cards
    resources :emps
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    root "welcome#index"
    
    resources :emps do
        resources :cards
    end
  
  
    get 'sign_up', to: 'emps#new'
    post 'sign_up', to: 'emps#create'
    
    get 'sign_in', to: 'sessions#new'
    post 'sign_in', to: 'sessions#create', as: 'log_in'
    delete 'logout', to: 'sessions#destroy'
    
    get 'password', to: 'passwords#edit', as: 'edit_password'
    patch 'password', to: 'passwords#update'
    get 'password/reset', to: 'password_resets#new'
    post 'password/reset', to: 'password_resets#create'
    get 'password/reset/edit', to: 'password_resets#edit'
    patch 'password/reset/edit', to: 'password_resets#update'

end

app/models/emp.rb
class Emp < ApplicationRecord
     has_many :cards , dependent: :destroy

    def cards_count
        self.cards.size
    end
    
    # adds virtual attributes for authentication
     has_secure_password
     # validates email
     validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  before_action :set_emp, only: %i[ show edit update destroy ]
  skip_before_action :authorized, only: [:new, :create, :root]
  layout :false , only: [:new]
  
  # GET /emps or /emps.json
  def index
    @emps = Emp.all
  end

  # GET /emps/1 or /emps/1.json
  def show
      #if @emp.id != session[:emp_id]
      #  puts "not allowed"
      #end
  end

  # GET /emps/new
  def new
    @emp = Emp.new
  end

  # GET /emps/1/edit
  def edit
  end

  # POST /emps or /emps.json
  def create
    @emp = Emp.new(emp_params)

    respond_to do |format|
      if @emp.save
        
        session[:emp_id] = @emp.id
        
        format.html { redirect_to @emp, notice: "Emp was successfully created." }
        format.json { render :show, status: :created, location: @emp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emps/1 or /emps/1.json
  def update
    respond_to do |format|
      if @emp.update(emp_params)
        format.html { redirect_to @emp, notice: "Emp was successfully updated." }
        format.json { render :show, status: :ok, location: @emp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1 or /emps/1.json
  def destroy
    @emp.destroy
    respond_to do |format|
      format.html { redirect_to emps_url, notice: "Emp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp
      @emp = Emp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emp_params
      params.require(:emp).permit(:user_name, :employee_id, :role, :email, :isManager, :password , :password_confirmation)
    end
end

app/helpers/emp_helper.rb
module EmpHelper
end

app/views/emps/_form.html.erb
<%= form_for(emp) do |f| %>
  <% if emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% emp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :employee_id %>
    <%= f.text_field :employee_id %>
  </div>
  
  <div class="field">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>
  
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :isManager %>
    <%= f.text_field :isManager %>
  </div>
  
  <p>
    <%= f.label 'password' %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label 'password_confirmation' %><br>
    <%= f.password_field :password_confirmation %>
  </p>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', emp: @emp %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emp_path %>

app/views/emps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emps</h1>

<table>
  <thead>
    <tr>
      <th> Id </th>
      <th>User name</th>
      <th>Employee ID</th>
      <th>Role</th>
      <th>Email</th>
      <th>isManager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.id %></td>
        <td><%= emp.user_name %></td>
        <td><%= emp.employee_id %></td>
        <td><%= emp.role %></td>
        <td><%= emp.email %></td>
        <td><%= emp.isManager %></td>
        <td><%= link_to 'Show', emp %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp', new_emp_path %>

app/views/emps/new.html.erb
<h1>New Emp</h1>

<%= render 'form', emp: @emp %>
<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
  <% if @emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% @emp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<p>
  <strong>ID:</strong>
  <%= @emp.id %>
</p>

<p>
  <strong>User name:</strong>
  <%= @emp.user_name %>
</p>

<p>
  <strong>Employee ID:</strong>
  <%= @emp.employee_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @emp.role %>
</p>

<p>
  <strong>Email:</strong>
  <%= @emp.email %>
</p>


<p>
  <strong>isManager:</strong>
  <%= @emp.isManager %>
</p>

<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %> |
<%= link_to 'Add Card', new_emp_card_path(@emp) %>


<h2>Cards</h2>
<!--%= render @emp.cards %-->
<%= render partial: "/cards/card", collection: @emp.cards, as: :c || "There are no cards available."  %>